"""
Train Visual CNN (Xception) on FaceForensics++ C23 Sampled Frames
=================================================================

This script trains the Xception visual baseline on extracted frame-level
samples from the FaceForensics++ C23 dataset. It is designed to work with
hashed/safe-id frame folders generated by the frame extraction pipeline.

Folder layout:
  data/interim/frames/FaceForensics++_C23/<split>/<SAFE_ID>/frame_000.jpg ...

Labels are obtained by joining:
  - split CSV (video_path -> label)
  - _id_map.csv in frames folder (safe_id -> video_path)

This approach keeps extracted frame folders anonymised while still allowing
them to be linked back to the correct ground-truth labels.

Run:
  python -m ml.train_xception

Author: Giulio Dajani 001343717
Project: VerifAI – Deepfake Detection Framework
Copyright © 2026 Giulio Labs
"""

# Add project root to the Python path so internal modules can be imported
import sys
from pathlib import Path
sys.path.append(str(Path(__file__).resolve().parents[1]))

# Standard libraries
import random
import csv

# Numerical computing
import numpy as np

# PyTorch core modules
import torch
import torch.nn as nn
from torch.utils.data import DataLoader, Dataset

# torchvision transforms for image preprocessing
from torchvision import transforms

# tqdm for progress bars during training/validation
from tqdm import tqdm

# PIL for image loading
from PIL import Image

# Evaluation metrics
from sklearn.metrics import roc_auc_score, f1_score

# Import Xception model builder
from ml.models.video.xception import build_xception_binary

# Logging utilities for experiment tracking
from scripts.curve_writer import append_curve_row
from scripts.run_logger import log_run, log_exception


# ==============================
# Configuration
# ==============================

# Root folder containing extracted frame datasets
DATA_ROOT = Path("data/interim/frames/FaceForensics++_C23")

# Output folder for saving trained model checkpoints
OUT_DIR = Path("experiments/results/ffpp_c23_xception_baseline")

# Train/validation split CSV files
TRAIN_SPLIT_CSV = Path("data/splits/faceforensics++_c23_train.csv")
VAL_SPLIT_CSV = Path("data/splits/faceforensics++_c23_val.csv")

# Xception standard image size
IMG_SIZE = 299

# Batch sizes for training and validation
BATCH_TRAIN = 16
BATCH_VAL = 32

# Number of training epochs
EPOCHS = 5

# Learning rate for AdamW optimizer
LR = 1e-4

# Number of worker processes for data loading
# Set to 0 for safer behavior on Windows/OneDrive
NUM_WORKERS = 0

# Fixed random seed for reproducibility
SEED = 42


def set_seed(seed: int):
    """
    Set all relevant random seeds.

    This improves reproducibility so that dataset shuffling and model
    initialization behave more consistently across runs.
    """
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    if torch.cuda.is_available():
        torch.cuda.manual_seed_all(seed)


def make_transforms(train: bool):
    """
    Build preprocessing pipeline for input frames.

    Training includes light augmentation (horizontal flip),
    while validation uses deterministic transforms only.
    """
    if train:
        return transforms.Compose([
            transforms.Resize((IMG_SIZE, IMG_SIZE)),
            transforms.RandomHorizontalFlip(p=0.5),
            transforms.ToTensor(),
            transforms.Normalize(mean=[0.485, 0.456, 0.406],
                                 std=[0.229, 0.224, 0.225]),
        ])

    return transforms.Compose([
        transforms.Resize((IMG_SIZE, IMG_SIZE)),
        transforms.ToTensor(),
        transforms.Normalize(mean=[0.485, 0.456, 0.406],
                             std=[0.229, 0.224, 0.225]),
    ])


def _norm_path(s: str) -> str:
    """
    Normalize path strings for reliable joining between CSV files.

    This avoids mismatches caused by slash direction or capitalization.
    """
    return str(s).strip().replace("\\", "/").lower()


def _load_video_path_to_label(split_csv: Path) -> dict[str, int]:
    """
    Load mapping: normalized video_path -> label from split CSV.

    Expected columns:
    - video_path
    - label
    """
    if not split_csv.exists():
        raise FileNotFoundError(f"Split CSV not found: {split_csv}")

    mapping: dict[str, int] = {}
    with split_csv.open("r", encoding="utf-8") as f:
        reader = csv.DictReader(f)

        if reader.fieldnames is None:
            raise ValueError(f"Split CSV has no header: {split_csv}")

        if "video_path" not in reader.fieldnames or "label" not in reader.fieldnames:
            raise ValueError(
                f"Split CSV must contain columns video_path,label. Found: {reader.fieldnames}"
            )

        for row in reader:
            vp = _norm_path(row["video_path"])
            lab = int(row["label"])
            mapping[vp] = lab

    if not mapping:
        raise ValueError(f"No rows loaded from split CSV: {split_csv}")

    return mapping


def _load_safeid_to_label_from_idmap(frames_split_dir: Path, split_csv: Path) -> dict[str, int]:
    """
    Build mapping: safe_id -> label by joining:
      - frames_split_dir/_id_map.csv  (safe_id, video_path)
      - split_csv                     (video_path, label)

    This is necessary because extracted frame folders are stored using
    anonymized SAFE_ID names rather than original video filenames.
    """
    id_map_path = frames_split_dir / "_id_map.csv"
    if not id_map_path.exists():
        raise FileNotFoundError(
            f"Missing {id_map_path}. Re-run extract_frames_from_csv.py for this split to generate it."
        )

    path_to_label = _load_video_path_to_label(split_csv)

    safeid_to_label: dict[str, int] = {}
    missing = 0
    example = None

    with id_map_path.open("r", encoding="utf-8") as f:
        reader = csv.DictReader(f)

        if reader.fieldnames is None:
            raise ValueError(f"_id_map.csv has no header: {id_map_path}")

        needed = {"safe_id", "video_path"}
        if not needed.issubset(set(reader.fieldnames)):
            raise ValueError(
                f"_id_map.csv must contain columns: safe_id,video_path. Found: {reader.fieldnames}"
            )

        for row in reader:
            sid = str(row["safe_id"]).strip()
            vp = _norm_path(row["video_path"])

            if vp in path_to_label:
                safeid_to_label[sid] = int(path_to_label[vp])
            else:
                missing += 1
                if example is None:
                    example = row

    if not safeid_to_label:
        raise ValueError(
            f"Join produced 0 labels for split {frames_split_dir}. "
            f"Check that video_path strings in split CSV match _id_map.csv.\n"
            f"Example missing row: {example}"
        )

    if missing > 0:
        print(f"[WARN] {missing} id_map rows had video_path not found in split CSV (ok if id_map contains extra).")

    return safeid_to_label


class FFPPFramesSafeIdDataset(Dataset):
    """
    Frame-level dataset using SAFE_ID folder names for label lookup.

    Structure:
      root_dir/<SAFE_ID>/frame_000.jpg ...
    """

    def __init__(self, root_dir: Path, safeid_to_label: dict[str, int], transform=None, strict: bool = True):
        self.root_dir = Path(root_dir)
        self.safeid_to_label = safeid_to_label
        self.transform = transform
        self.strict = strict

        # Collect all image files under the split folder
        image_paths = []
        image_paths.extend(self.root_dir.rglob("*.jpg"))
        image_paths.extend(self.root_dir.rglob("*.jpeg"))
        image_paths.extend(self.root_dir.rglob("*.png"))
        image_paths = sorted(image_paths)

        if not image_paths:
            raise FileNotFoundError(f"No frames found under: {self.root_dir}")

        filtered = []
        missing = 0
        example_missing = None

        # Keep only frames whose SAFE_ID appears in the label map
        for p in image_paths:
            safe_id = p.parent.name
            if safe_id in self.safeid_to_label:
                filtered.append(p)
            else:
                missing += 1
                if example_missing is None:
                    example_missing = p

        # In strict mode, any mismatch is treated as a dataset integrity issue
        if strict and missing > 0:
            raise KeyError(
                f"{missing} frame(s) have SAFE_ID not found in labels map. "
                f"Example path: {example_missing}. "
                "This means your frames were extracted with an _id_map.csv that doesn't match the split CSV."
            )

        self.image_paths = filtered

        if not self.image_paths:
            raise ValueError(
                f"After filtering by labels map, dataset is empty for root: {self.root_dir}."
            )

    def __len__(self) -> int:
        """Return total number of frame samples."""
        return len(self.image_paths)

    def __getitem__(self, idx: int):
        """
        Load one frame sample and return:
        - transformed image tensor
        - label tensor
        - safe_id for traceability
        """
        path = self.image_paths[idx]
        safe_id = path.parent.name
        label = float(self.safeid_to_label[safe_id])

        img = Image.open(path).convert("RGB")
        if self.transform is not None:
            img = self.transform(img)

        return img, torch.tensor(label), safe_id


def main():
    """
    Main training pipeline for the Xception baseline.

    This function:
    - loads dataset labels via safe_id joining
    - builds training/validation datasets
    - trains the model
    - evaluates on validation set
    - saves the best checkpoint
    - logs metrics and artifacts
    """
    run_name = "xception_baseline"
    curve_csv = f"experiments/logs/training_curves/{run_name}.csv"

    try:
        set_seed(SEED)

        OUT_DIR.mkdir(parents=True, exist_ok=True)
        best_path = OUT_DIR / "best_model.pt"

        train_dir = DATA_ROOT / "train"
        val_dir = DATA_ROOT / "val"

        device = "cuda" if torch.cuda.is_available() else "cpu"
        print("Device:", device)

        # Build SAFE_ID -> label mappings by joining _id_map.csv with split CSV
        train_labels = _load_safeid_to_label_from_idmap(train_dir, TRAIN_SPLIT_CSV)
        val_labels = _load_safeid_to_label_from_idmap(val_dir, VAL_SPLIT_CSV)

        # Build datasets
        train_ds = FFPPFramesSafeIdDataset(
            train_dir,
            safeid_to_label=train_labels,
            transform=make_transforms(train=True),
            strict=True
        )
        val_ds = FFPPFramesSafeIdDataset(
            val_dir,
            safeid_to_label=val_labels,
            transform=make_transforms(train=False),
            strict=True
        )

        print("Train frames:", len(train_ds))
        print("Val frames:", len(val_ds))

        # Build dataloaders
        train_loader = DataLoader(
            train_ds,
            batch_size=BATCH_TRAIN,
            shuffle=True,
            num_workers=NUM_WORKERS
        )
        val_loader = DataLoader(
            val_ds,
            batch_size=BATCH_VAL,
            shuffle=False,
            num_workers=NUM_WORKERS
        )

        # Build model and move to selected device
        model = build_xception_binary(pretrained=True).to(device)

        # Binary classification loss and optimizer
        loss_fn = nn.BCEWithLogitsLoss()
        optimizer = torch.optim.AdamW(model.parameters(), lr=LR)

        best_val_loss = float("inf")
        best_epoch = 0
        best_val_auc = float("nan")
        best_val_f1 = float("nan")

        for epoch in range(1, EPOCHS + 1):

            # -------------------------
            # Training phase
            # -------------------------
            model.train()
            train_loss_sum = 0.0
            train_count = 0

            for images, labels, safe_ids in tqdm(train_loader, desc=f"Epoch {epoch}/{EPOCHS} - train"):
                images = images.to(device)
                labels = labels.float().to(device)

                logits = model(images).squeeze(1)
                loss = loss_fn(logits, labels)

                optimizer.zero_grad()
                loss.backward()
                optimizer.step()

                bs = images.size(0)
                train_loss_sum += loss.item() * bs
                train_count += bs

            train_loss = train_loss_sum / max(train_count, 1)

            # -------------------------
            # Validation phase
            # -------------------------
            model.eval()
            val_loss_sum = 0.0
            val_count = 0

            all_labels = []
            all_probs = []

            with torch.no_grad():
                for images, labels, safe_ids in tqdm(val_loader, desc=f"Epoch {epoch}/{EPOCHS} - val"):
                    images = images.to(device)
                    labels = labels.float().to(device)

                    logits = model(images).squeeze(1)
                    loss = loss_fn(logits, labels)

                    probs = torch.sigmoid(logits)

                    bs = images.size(0)
                    val_loss_sum += loss.item() * bs
                    val_count += bs

                    all_labels.extend(labels.detach().cpu().numpy().tolist())
                    all_probs.extend(probs.detach().cpu().numpy().tolist())

            val_loss = val_loss_sum / max(val_count, 1)

            # ROC-AUC only makes sense if both classes are present
            val_auc = float("nan")
            if len(set(all_labels)) > 1:
                val_auc = roc_auc_score(all_labels, all_probs)

            # Convert probabilities to binary predictions for F1 calculation
            preds = (np.array(all_probs) >= 0.5).astype(int).tolist()
            val_f1 = f1_score(all_labels, preds, zero_division=0)

            print(
                f"Epoch {epoch}: train_loss={train_loss:.4f}  val_loss={val_loss:.4f}  "
                f"val_auc={val_auc:.4f}  val_f1={val_f1:.4f}"
            )

            # Save checkpoint if validation loss improves
            if val_loss < best_val_loss:
                best_val_loss = val_loss
                best_epoch = epoch
                best_val_auc = val_auc
                best_val_f1 = val_f1

                torch.save({
                    "model_state": model.state_dict(),
                    "val_loss": best_val_loss,
                    "val_auc": best_val_auc,
                    "val_f1": best_val_f1,
                    "epoch": best_epoch,
                    "config": {
                        "model": "xception",
                        "img_size": IMG_SIZE,
                        "epochs": EPOCHS,
                        "lr": LR,
                        "seed": SEED,
                        "batch_train": BATCH_TRAIN,
                        "batch_val": BATCH_VAL,
                        "num_workers": NUM_WORKERS,
                        "data_root": str(DATA_ROOT),
                        "train_split_csv": str(TRAIN_SPLIT_CSV),
                        "val_split_csv": str(VAL_SPLIT_CSV),
                        "label_source": "_id_map.csv join on video_path",
                    }
                }, best_path)
                print("Saved best ->", best_path)

            # Append epoch metrics to training curve log
            append_curve_row(curve_csv, {
                "epoch": epoch,
                "train_loss": train_loss,
                "val_loss": val_loss,
                "val_auc": val_auc,
                "val_f1": val_f1,
            })

        # Log run summary for experiment tracking
        log_run(run_name, payload={
            "task": "train",
            "model": "xception",
            "dataset": "FaceForensics++_C23",
            "split": "train/val",
            "seed": SEED,
            "metrics": {
                "best_val_loss": best_val_loss,
                "best_epoch": best_epoch,
                "best_val_auc": best_val_auc,
                "best_val_f1": best_val_f1,
            },
            "artifacts": [str(best_path), str(curve_csv)],
            "notes": "Frame folders use SAFE_ID from extractor. Labels joined via _id_map.csv + split CSV video_path.",
        })

        print("Done. Best val loss:", best_val_loss)

    except Exception as exc:
        # Log exception details before re-raising,
        # so failed runs are still traceable
        log_exception(run_name, exc, context={"script": "ml/train_xception.py"})
        raise


if __name__ == "__main__":
    main()